
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 22 03:28:15 EDT 2011
//----------------------------------------------------

package mycc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 11;
  public static final int PLUS = 14;
  public static final int RPAREN = 19;
  public static final int NE_OP = 3;
  public static final int INT = 7;
  public static final int SEMI = 24;
  public static final int LCURL = 22;
  public static final int WHILE = 12;
  public static final int CONSTANT = 29;
  public static final int IDENTIFIER = 30;
  public static final int RETURN = 13;
  public static final int AND_OP = 4;
  public static final int IF = 10;
  public static final int LBRACKET = 20;
  public static final int LPAREN = 18;
  public static final int EQ_OP = 2;
  public static final int NOT_OP = 6;
  public static final int GR = 27;
  public static final int RBRACKET = 21;
  public static final int STRING_LITERAL = 31;
  public static final int COMMA = 25;
  public static final int EOF = 0;
  public static final int DIV = 16;
  public static final int OR_OP = 5;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int ASSIGN = 28;
  public static final int BOOL = 9;
  public static final int RCURL = 23;
  public static final int MUL = 17;
  public static final int VOID = 8;
  public static final int LESS = 26;
}

