#!/bin/csh
foreach prog (01 02 03 04 05 06 07 08)
        echo "////////////////////////////////////////////////////"
        echo "///////////// parsing test$prog.c //////////////////////"
        echo "////////////////////////////////////////////////////"
        java mycc.parser test$prog.c > test$prog.log
        java test$prog >> test$prog.log
        echo ""
end

foreach prog (09 10)
        echo "////////////////////////////////////////////////////"
        echo "///////////// parsing test$prog.c //////////////////////"
        echo "////////////////////////////////////////////////////"
        java mycc.parser -O test$prog.c > test$prog.log
        java test$prog >> test$prog.log
        echo ""
end